# Generated by Django 3.1.3 on 2021-03-25 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210325_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='iimageLink',
            new_name='imageLink',
        ),
    ]
