# Generated by Django 3.1.3 on 2021-03-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='Title',
            field=models.CharField(default='unavailable', max_length=100),
            preserve_default=False,
        ),
    ]
