# Generated by Django 3.1.3 on 2021-03-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_store_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='Book',
        ),
        migrations.AddField(
            model_name='store',
            name='Book',
            field=models.ManyToManyField(to='store.Book'),
        ),
    ]
