# Generated by Django 3.1.3 on 2021-03-28 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210326_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='imageLink',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='storebooks',
            name='Book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.book'),
        ),
    ]
