# Generated by Django 3.1.3 on 2021-03-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210328_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='imageLink',
            field=models.CharField(max_length=500),
        ),
    ]
