# Generated by Django 3.1.3 on 2021-03-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Authors',
            field=models.CharField(default='undefined', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='iimageLink',
            field=models.CharField(default='undefined', max_length=100),
            preserve_default=False,
        ),
    ]
